#!/usr/bin/env python3
"""Generate the C++ AST kind constants from the reviewed kind manifest."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATOR_DIR = Path(__file__).resolve().parent
UINT32_MAX = (1 << 32) - 1

if str(GENERATOR_DIR) not in sys.path:
    sys.path.insert(0, str(GENERATOR_DIR))

import bootstrap_kind_manifest  # noqa: E402


class KindHeaderError(ValueError):
    """A valid C++ kind header cannot be generated from the manifest."""


def _enum_name(cpp_type: str) -> str:
    """Map a qualified C++ type to an ASCII-only enum member identifier."""
    # Treat namespace separators as a single separator, then map every other
    # non-ASCII identifier character to an underscore. The explicit ranges
    # avoid locale-dependent character classes.
    flattened = cpp_type.replace("::", "_")
    return re.sub(r"[^A-Za-z0-9_]", "_", flattened)


def _cpp_string(value: str) -> str:
    """Return a deterministic C++ string literal for a UTF-8 source value."""
    escaped: list[str] = ['"']
    for char in value:
        codepoint = ord(char)
        if char == '"':
            escaped.append(r'\"')
        elif char == "\\":
            escaped.append(r"\\")
        elif char == "\n":
            escaped.append(r"\n")
        elif char == "\r":
            escaped.append(r"\r")
        elif char == "\t":
            escaped.append(r"\t")
        elif codepoint < 0x20 or codepoint == 0x7F:
            # The adjacent literals terminate a hexadecimal escape before the
            # next character, which could otherwise extend its value.
            escaped.append(f"\\x{codepoint:02x}\"\"")
        else:
            escaped.append(char)
    escaped.append('"')
    return "".join(escaped)


def render_header(document: Any) -> str:
    """Validate a manifest and return the generated C++17 header text."""
    kinds = bootstrap_kind_manifest.read_manifest(document)
    if not kinds:
        raise KindHeaderError("kind manifest must contain at least one kind")

    enum_names: dict[str, str] = {}
    for item in kinds:
        kind_id = item["id"]
        if kind_id > UINT32_MAX:
            raise KindHeaderError(
                f"kind ID {kind_id} for {item['cpp_type']} does not fit uint32_t"
            )
        cpp_type = item["cpp_type"]
        enum_name = _enum_name(cpp_type)
        previous = enum_names.get(enum_name)
        if previous is not None:
            raise KindHeaderError(
                f"C++ enum name collision {enum_name!r}: {previous!r} and {cpp_type!r}"
            )
        enum_names[enum_name] = cpp_type

    lines = [
        "// Generated by generator/generate_kind_header.py from generator/kinds.json.",
        "// Do not edit this file by hand.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace flang_dumper {",
        "",
        "enum class AstKind : std::uint32_t {",
    ]
    for item in kinds:
        lines.append(
            f"  {_enum_name(item['cpp_type'])} = {item['id']}U,"
        )
    lines.extend(
        [
            "};",
            "",
            "struct AstKindInfo {",
            "  AstKind kind;",
            "  std::uint32_t id;",
            "  std::string_view cpp_type;",
            "  std::string_view handler_kind;",
            "};",
            "",
            "inline constexpr AstKindInfo kAstKinds[] = {",
        ]
    )
    for item in kinds:
        lines.append(
            "  {AstKind::"
            f"{_enum_name(item['cpp_type'])}, {item['id']}U, "
            f"{_cpp_string(item['cpp_type'])}, {_cpp_string(item['handler_kind'])}}},"
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr std::size_t kAstKindCount =",
            "    sizeof(kAstKinds) / sizeof(kAstKinds[0]);",
            "",
            "constexpr const AstKindInfo* find_ast_kind_by_id(std::uint32_t id) noexcept {",
            "  for (const auto& kind : kAstKinds) {",
            "    if (kind.id == id) {",
            "      return &kind;",
            "    }",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "constexpr const AstKindInfo* find_ast_kind_by_cpp_type(",
            "    std::string_view cpp_type) noexcept {",
            "  for (const auto& kind : kAstKinds) {",
            "    if (kind.cpp_type == cpp_type) {",
            "      return &kind;",
            "    }",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "}  // namespace flang_dumper",
            "",
        ]
    )
    return "\n".join(lines)


def _read_manifest(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise KindHeaderError(f"cannot read manifest {path}: {error}") from error
    except json.JSONDecodeError as error:
        raise KindHeaderError(f"invalid JSON in manifest {path}: {error}") from error


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=REPO_ROOT / "generator" / "kinds.json",
        help="kind manifest to read (default: generator/kinds.json)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "protocol" / "ast_kinds.hpp",
        help="header to write or check (default: protocol/ast_kinds.hpp)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if --output differs byte-for-byte from generated content",
    )
    args = parser.parse_args(argv)

    try:
        if args.output.resolve() == args.manifest.resolve():
            raise KindHeaderError("output path must not overwrite the input manifest")
        contents = render_header(_read_manifest(args.manifest)).encode("utf-8")
        if args.check:
            try:
                current = args.output.read_bytes()
            except OSError as error:
                raise KindHeaderError(f"cannot read output {args.output}: {error}") from error
            if current != contents:
                print(f"kind header is stale: {args.output}", file=sys.stderr)
                return 1
            print(f"kind header is fresh: {args.output}")
            return 0

        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(contents)
    except (bootstrap_kind_manifest.ManifestError, KindHeaderError) as error:
        print(f"kind header error: {error}", file=sys.stderr)
        return 2
    except OSError as error:
        print(f"kind header error: {error}", file=sys.stderr)
        return 2

    print(f"Wrote kind header to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
